- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}/facts.d"
        state: directory
    - name: "Insert custom fact file"
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/facts.d/"
      with_fileglob: "/etc/ansible/facts/*.fact"
    - name: "Re-run setup to use custom facts"
      setup: ~
        fact_path: "{{ ansible_user_dir }}/facts.d"
        
