- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Re-run setup to use custom facts"
      setup: ~
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}/facts.d"
        state: directory
    - name: "Insert custom fact file"
      copy:
        src: "{{ item }}"
        dest: /etc/ansible/facts.d/custom.fact
      with_fileglob: "/etc/ansible/facts/{{ copy }}*.fact"
        
