- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Re-run setup to use custom facts"
      setup: ~
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}/facts.d"
        state: directory
    - name: Ejecutar sh
      shell: /home/altabox/pruebas/recopilar.sh
      register: recopilaDatos
    - debug:
        msg: "RESULTADO: {{ recopilaDatos.stdout }}"
        msg: "split: {{  recopilaDatos.stdout.split(';') }}"
        
    - name: Array
      set_fact: 
        psk={{ item }}
      with_items:
      - "{{ recopilaDatos.stdout.split(';') }}"
    
