- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Re-run setup to use custom facts"
      setup: ~
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}/facts.d"
        state: directory
