- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}"/facts.d
        state: directory
        recurse: yes
    - name: "Insert custom fact file"
      copy:
        src: files/custom.fact
        dest: "{{ ansible_user_dir }}"/facts.d
        mode: 0755
    - name: "Re-run setup to use custom facts"
      setup: filter=ansible_local
    
