- name: MIGRACION - Recopilar datos con facts
  strategy: free
  hosts: all
  tasks:
    - name: "Create custom fact directory"
      file:
        path: "{{ ansible_user_dir }}/facts.d"
        state: directory 
    - name: "Sincronizar carpetas facts"
      synchronize:
        src: "/etc/ansible/facts"
        dest: "{{ ansible_user_dir }}/facts.d"
