- name: MIGRACION - Recopilar datos con facts
  hosts: all
  tasks:
    - name: "Re-run setup to use custom facts"
      setup: ~
    - name: "Create custom fact directory"
      file:
        path: "/home/migracion/facts"
        state: "directory"
    - name: "Insert custom fact file"
      copy:
        src: files/custom.fact
        dest: /home/migracion/facts/custom.fact
        mode: 0755
