- name: MIGRACION - Finalizar
  hosts: all
  gather_facts: no
  tasks:   
    - name: Ejecutar scripts de Finalizar
      shell: wget -O - http://10.44.36.65/migracion/scripts_llaollao/000-commons.sh | bash -s '500-finalizar.sh'     
