- name: MIGRACION - Copiar archivos APT
  hosts: all
  gather_facts: no
  tasks:
    - name: Copiar archivos APT
      shell: wget -nc -r -nv -np -nH --cut-dirs=2 -P /home/altabox/migracion/apt -e robots=off --reject='index.html*' -X /icons http://10.44.36.65/migracion/apt/  
      register: resultado
      failed_when: >
        ("# Error en script" in resultado.stdout)
        
