- name: MIGRACION - Recopilar datos con facts
  strategy: free
  hosts: all
  tasks:
    - name: "Create custom fact directory"
      file:
        path: "/root/facts.d"
        state: directory
    - name: "Insert custom fact file"
      copy:
        src: "{{ item }}"
        dest: "/root/facts.d/"
        mode: 0755
      with_fileglob: "/etc/ansible/facts/*.fact" 
